# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_asynchttp_wrappers", use_symbols = TRUE, package_name = "asynchttp")

#' @usage NULL
#' @useDynLib asynchttp, .registration = TRUE
NULL

RequestBuilder <- new.env(parent = emptyenv())

RequestBuilder$new <- function(verb, url) .Call(wrap__RequestBuilder__new, verb, url)

RequestBuilder$set_header <- function(header_name, header_value) invisible(.Call(wrap__RequestBuilder__set_header, self, header_name, header_value))

RequestBuilder$set_body_raw <- function(body) invisible(.Call(wrap__RequestBuilder__set_body_raw, self, body))

RequestBuilder$send_request <- function(http_client) .Call(wrap__RequestBuilder__send_request, self, http_client)

#' @export
`$.RequestBuilder` <- function (self, name) { func <- RequestBuilder[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RequestBuilder` <- `$.RequestBuilder`

HttpClient <- new.env(parent = emptyenv())

HttpClient$new <- function(num_threads) .Call(wrap__HttpClient__new, num_threads)

#' @export
`$.HttpClient` <- function (self, name) { func <- HttpClient[[name]]; environment(func) <- environment(); func }

#' @export
`[[.HttpClient` <- `$.HttpClient`

Response <- new.env(parent = emptyenv())

Response$poll <- function() .Call(wrap__Response__poll, self)

Response$get_content_string <- function() .Call(wrap__Response__get_content_string, self)

#' @export
`$.Response` <- function (self, name) { func <- Response[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Response` <- `$.Response`


# nolint end
